version: "3"

services:
  web:
    #image: "childb/myfirstapp:3.0"
    build: .
    environment:
      - MESSAGE="MINHA_APP"
    networks:
      lab1:
        ipv4_address: 172.20.0.2
    ports:
      - "80:80"

    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/srv/redis/data:/data"

    command: "redis-server --appendonly yes"
    networks:
      lab1:
        ipv4_address: 172.20.0.3

networks:
  lab1:
    ipam:
      config:
        - subnet: 172.20.0.0/24

